### ISSUE TITLE
hasPermission issue

### ISSUE THREAD

**Issue by andim27** [nylo-core/permission_policy#2]
If use next:
```
  bool res = false;
 String namePermission = 'my_permission';
  List<String> roles = await PermissionPolicy.getRoles();
    for (String role in roles) {
      List<String> permissions = PermissionPolicy.instance.findPermissionsForRole(role);
      if (permissions.contains(namePermission)) {
        res = true;
      }
    }
```
This works, but if use next:
`res = await PermissionPolicy.hasPermission(namePermission)`
it always return False
Why?
Please check

**Comment by agordn52** [comment]
Hi @andim27,

Hope you are well.
I've just tested this and the behavior works as expected.

The `List<String> roles = await PermissionPolicy.getRoles();` method will return the users roles.
If they don't have a 'role' in your app, this method will return an empty array.

To give a user a role, you can use the `await PermissionPolicy.giveRole("my_role");` method.
